### ISSUE TITLE
To Do List for ATG Merge

### ISSUE THREAD

**Issue by lduarte1991** [lduarte1991/hxat#33]
- [x] Link Instructor dashboard to ZoomToImage and ZoomToQuote function
- [x] Testing Instructor dashboard on handling a large number of annotations
- [x] Double check with Justin about whether annotations are actually deleted
- [x] Talk to Justin about memory/slow down issues when asking for a lot of annotations
- [x] Limiting Manifests URL to 1 per Target Object + enforce 1-to-1 relationship between the two.
- [ ] Change name used in detail.html from Target Object title to assignment name (default) or a name attribute in AssignmentTargets
- [x] Remove need for citation in Target Object (add errors to form)
- [ ] Test everything!!!

**Comment by lduarte1991** [comment]
@arthurian Seems like annotations are not actually deleted, they are just marked as deleted, though there does exist a "destroy" function to permanently delete them. Will update with answer to question about whether we should be checking for that or if the catch handles it.

He hasn't had time to check the memory/slow down issues based on limits, but hopefully will have some time in the next couple of weeks to check it out. will keep you updated on that too.

**Comment by arthurian** [comment]
@lduarte1991 Good to know our assumption was right on the delete issue, and that there's a destroy function.

If I have any time, I might take a peak at that code and see if I can make heads or tails of it, but yeah, hopefully Justin can get to that in the next few weeks.

**Comment by lduarte1991** [comment]
So I just tried the Instructor dashboard with about 400ish annotations and it took around 6seconds to load up. Not ideal, but also not entirely terrible. I may try in a bit with a thousand or two and see how that does. There is one issue I'm having problems with, because you are using the user id to collapse and open the table with the annotations, we are having some issues with annotations we transferred in from our old tool that use emails as the id. apparently having an @ or a . stop it from actually opening and closing. Can you change that to just be an arbitrary number (counter going up?) or something else. Once I go in and edit the id and toggle, they open up just fine and the annotations and everything are there.

**Comment by arthurian** [comment]
Any idea where the performance bottleneck is? Is it on the CATCH database side or more on the django view side of things? (i.e. 6 seconds to fetch from the CATCH and <1 second to render the view?)

I'll go ahead fix that issue with the ```user_id``` so it's an arbitrary number and send you a PR. I keep forgetting that the ```user_id``` isn't always a hash-type entity and that it can contain emails.

**Comment by lduarte1991** [comment]
Well it shouldn't from now on....but you never know when an instructor is going to want to bring in stuff from the horrid horrid past. 

And I haven't looked into the bottleneck yet. It's hard to get info on it via the browser because the page just doesn't load until after everything is loaded, which would normally make me think it's a django and not a CATCH issue, but you guys do the network calls before the page gets resolves and not after so it could still be CATCH. I can look into if after a few small UI/CSS bugs I discovered.

**Comment by arthurian** [comment]
Yeah we want to be safe in such cases. I just submitted https://github.com/lduarte1991/hx-annotations-lti/pull/36 which should fix the issue.

Oh one thing I'd be curious to see is what the timer says on the instructor dashboard (bottom right hand side). Here's an example of what it looks like for my local instance:

![screen shot 2015-11-05 at 12 26 58 pm](https://cloud.githubusercontent.com/assets/1165361/10976258/d3a7c190-83b8-11e5-8bb7-b013ef80b96b.png)

You can see in the view that the timer just measures roughly how long it takes to make the request to the CATCH database. It doesn't include the time to transform/render the data to the view, so between that timer and the page load time in the browser, we should be able to get a rough idea of where the bottleneck is.

**Comment by arthurian** [comment]
One other thing: not sure if you saw my comment on https://github.com/annotationsatharvard/catcha/issues/72 yesterday, but I did a little investigating and I *think* I figured out why search performance deteriorates as the number of annotations increases. Not sure exactly how to fix it though, as my groovy/grails skills are nil, but maybe you could bring it to Justin's attention.

**Comment by lduarte1991** [comment]
I did see that and I messaged him about it. Not sure when he'll get a chance to tackle it though.

And I just ran it and it seems like it "Loaded annotations in 2.4130 seconds".

**Comment by arthurian** [comment]
The page still takes ~6 seconds to load? That's pretty bad. Might need a different strategy on the django side of things if it's ~2 seconds to load from catch and ~4 seconds to render the view in django.

Thanks for messaging him about it. I just saw that he responded to the issue and from what he said, it sounds like a reasonably straightforward fix on his end. Hopefully he can make the necessary change and push out a new release soon so we can both benefit.

**Comment by lduarte1991** [comment]
I'm getting 5.74s to load the page and 3.0055s from the timer you added.

**Comment by lduarte1991** [comment]
So..I think I'm happy with what we have so far for the merge and have had a few people test out as much as possible. I think I'm gonna change the naming conventions after the merge since I'm planning to add stuff immediately after that deals with the assignmenttargets database anyway so it makes sense to lump it in with that. So I'm gonna give my :+1: for this merge.

**Comment by arthurian** [comment]
Great! Looks good to me too. Shannon and some other folks are testing it, but so far so good on our end. 

I think you're right about splitting the dashboard so that the page loads first and then asynchronously loads the annotations, that way the perceived load time is less/more bearable. I'll wait to do that until after the merge. 

:+1:

**Comment by lduarte1991** [comment]
Alright sounds good! I shall merge momentarily. Then I'll double check with my course leads and let them know I will be updating productions. *fingers crossed*

**Comment by arthurian** [comment]
Good luck! *Fingers double crossed*

**Comment by arthurian** [comment]
One follow-up question: after you deploy to production, would it be a good idea to tag the [release](https://github.com/lduarte1991/hx-annotations-lti/releases)? 

That's something we've recently started doing... makes it handy to audit exactly which revisions have been deployed to production later. You can see an example of what we've been doing [here](https://github.com/Harvard-ATG/annotationsx/releases).

**Comment by lduarte1991** [comment]
Seems like a good idea to me! Not sure what numbering convention you follow. I'm assuming v1.1 since it's a bigger release than your last 1.0.6?

Seems like everything is working well in our production end. Only down for 10-15 mins while I figured out where the http_static folder was supposed to be moved haha.

**Comment by arthurian** [comment]
Glad it went OK. Yeah the http_static folder... I've run into that before. 

Yeah, v1.1 sounds good. Assuming Shannon gives the OK on our end, we'll try and deploy it to production early next week.
