### ISSUE TITLE
Participation Grading

### ISSUE THREAD

**Issue by lduarte1991** [lduarte1991/hxat#57]
@arthurian wanted to get your thoughts on this topic.

I know that some courses like  Poetry in AmericaX and ChinaX have been recording participation grades by having the students answer a "Did you annotate the above?" question in a multiple choice assessment on the edX platform. I wanted to provide a way to do that in the tool, but I have a few questions.

Obviously, this needs to remain completely on the server side as we don't want the user to be able to trigger any events that could alter grades. This means that we basically are limited to recording grades when they make a call to catch. Right now I'm thinking of putting it into two places:

1) During annotation creation. When a user makes an annotation they get a score of 1 (scores are between 0.0 and 1.0).
2) During the annotation search. If they hit "My Notes" then the search call will contain the user_id. If they are searching for themselves (i.e. the user_id in the requests matches the one in the sessions) it will measure the length of rows returned from catch. If it's 0 (i.e. if they deleted their annotations) then set the score back to 0.0. If it's more than 0, then set it as 1.0 again. 

I'm a little (read: a lot) iffy on number 2. I think it's good so that we don't have people creating annotations and then deleting them just for a score and it's good to have a way for them to "resubmit" annotations. It's bad because there are many ways in which they can accidentally set their score to 0.0 and it's a very hidden/unintuitive way of going on about it. 

Overall thoughts?

**Comment by lduarte1991** [comment]
The more I talk to colleagues about it and the more I think about it, I think that #2 is unnecessary until we've actually thought through assessments in general....which is down the road after quite a few things that need to be fixed/added. I think #1 is still important because of the courses already doing adding that check. Is this something that should probably just exist in my own release branch and not on master? I'll make a PR so you can see a little bit more clearly what I intend to do.

**Comment by arthurian** [comment]
@lduarte1991 I think providing a way to record/assess student's participation would be very valuable to faculty in Canvas as well as edX. I'd be in favor of having this be a general feature on master. In particular, (1) seems like it would be immediately useful and intuitive to both students and faculty. I would agree that (2) is more complicated and would have some drawbacks, so it might be better to think that one through a little more in terms of how it would work with assessments overall.  I'll run this past Shannon and get his thoughts as well.

I'll keep an eye out for the PR to see what you have in mind.
